{% set name = "aiostream" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiostream-{{ version }}.tar.gz
  sha256: 3ecbf87085230fbcd9605c32ca20c4fb41af02c71d076eab246ea22e35947d88

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - async-exit-stack
    - python >=3.6

test:
  imports:
    - aiostream
    - aiostream.stream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vxgmichel/aiostream
  summary: Generator-based operators for asynchronous iteration
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ian-r-rose
    - shughes-uk
    - timkpaine
    - vxgmichel
